// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.1
// source: protobuf.proto

package packet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalingType int32

const (
	SignalingType_tSDP   SignalingType = 0
	SignalingType_tICE   SignalingType = 1
	SignalingType_tSTART SignalingType = 2
	SignalingType_tEND   SignalingType = 3
)

// Enum value maps for SignalingType.
var (
	SignalingType_name = map[int32]string{
		0: "tSDP",
		1: "tICE",
		2: "tSTART",
		3: "tEND",
	}
	SignalingType_value = map[string]int32{
		"tSDP":   0,
		"tICE":   1,
		"tSTART": 2,
		"tEND":   3,
	}
)

func (x SignalingType) Enum() *SignalingType {
	p := new(SignalingType)
	*p = x
	return p
}

func (x SignalingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalingType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_proto_enumTypes[0].Descriptor()
}

func (SignalingType) Type() protoreflect.EnumType {
	return &file_protobuf_proto_enumTypes[0]
}

func (x SignalingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalingType.Descriptor instead.
func (SignalingType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{0}
}

type SDP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	SDPData string `protobuf:"bytes,2,opt,name=SDPData,proto3" json:"SDPData,omitempty"`
}

func (x *SDP) Reset() {
	*x = SDP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDP) ProtoMessage() {}

func (x *SDP) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDP.ProtoReflect.Descriptor instead.
func (*SDP) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{0}
}

func (x *SDP) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SDP) GetSDPData() string {
	if x != nil {
		return x.SDPData
	}
	return ""
}

type ICE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Candidate     string `protobuf:"bytes,1,opt,name=Candidate,proto3" json:"Candidate,omitempty"`
	SDPMid        string `protobuf:"bytes,2,opt,name=SDPMid,proto3" json:"SDPMid,omitempty"`
	SDPMLineIndex int64  `protobuf:"varint,3,opt,name=SDPMLineIndex,proto3" json:"SDPMLineIndex,omitempty"`
}

func (x *ICE) Reset() {
	*x = ICE{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ICE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICE) ProtoMessage() {}

func (x *ICE) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICE.ProtoReflect.Descriptor instead.
func (*ICE) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{1}
}

func (x *ICE) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *ICE) GetSDPMid() string {
	if x != nil {
		return x.SDPMid
	}
	return ""
}

func (x *ICE) GetSDPMLineIndex() int64 {
	if x != nil {
		return x.SDPMLineIndex
	}
	return 0
}

type SignalingMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type SignalingType `protobuf:"varint,1,opt,name=type,proto3,enum=protobuf.SignalingType" json:"type,omitempty"`
	Sdp  *SDP          `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Ice  *ICE          `protobuf:"bytes,3,opt,name=ice,proto3" json:"ice,omitempty"`
}

func (x *SignalingMessage) Reset() {
	*x = SignalingMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalingMessage) ProtoMessage() {}

func (x *SignalingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalingMessage.ProtoReflect.Descriptor instead.
func (*SignalingMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_proto_rawDescGZIP(), []int{2}
}

func (x *SignalingMessage) GetType() SignalingType {
	if x != nil {
		return x.Type
	}
	return SignalingType_tSDP
}

func (x *SignalingMessage) GetSdp() *SDP {
	if x != nil {
		return x.Sdp
	}
	return nil
}

func (x *SignalingMessage) GetIce() *ICE {
	if x != nil {
		return x.Ice
	}
	return nil
}

var File_protobuf_proto protoreflect.FileDescriptor

var file_protobuf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x33, 0x0a, 0x03, 0x53, 0x44,
	0x50, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x44, 0x50, 0x44, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x44, 0x50, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x61, 0x0a, 0x03, 0x49, 0x43, 0x45, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x61, 0x6e, 0x64, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x44, 0x50, 0x4d, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x44, 0x50, 0x4d, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d,
	0x53, 0x44, 0x50, 0x4d, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x53, 0x44, 0x50, 0x4d, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x81, 0x01, 0x0a, 0x10, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x44, 0x50,
	0x52, 0x03, 0x73, 0x64, 0x70, 0x12, 0x1f, 0x0a, 0x03, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x49, 0x43,
	0x45, 0x52, 0x03, 0x69, 0x63, 0x65, 0x2a, 0x39, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x53, 0x44, 0x50, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x74,
	0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x45, 0x4e, 0x44, 0x10,
	0x03, 0x32, 0x54, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x47,
	0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_proto_rawDescOnce sync.Once
	file_protobuf_proto_rawDescData = file_protobuf_proto_rawDesc
)

func file_protobuf_proto_rawDescGZIP() []byte {
	file_protobuf_proto_rawDescOnce.Do(func() {
		file_protobuf_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_proto_rawDescData)
	})
	return file_protobuf_proto_rawDescData
}

var file_protobuf_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_proto_goTypes = []interface{}{
	(SignalingType)(0),       // 0: protobuf.SignalingType
	(*SDP)(nil),              // 1: protobuf.SDP
	(*ICE)(nil),              // 2: protobuf.ICE
	(*SignalingMessage)(nil), // 3: protobuf.SignalingMessage
}
var file_protobuf_proto_depIdxs = []int32{
	0, // 0: protobuf.SignalingMessage.type:type_name -> protobuf.SignalingType
	1, // 1: protobuf.SignalingMessage.sdp:type_name -> protobuf.SDP
	2, // 2: protobuf.SignalingMessage.ice:type_name -> protobuf.ICE
	3, // 3: protobuf.Signaling.handshake:input_type -> protobuf.SignalingMessage
	3, // 4: protobuf.Signaling.handshake:output_type -> protobuf.SignalingMessage
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_proto_init() }
func file_protobuf_proto_init() {
	if File_protobuf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SDP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ICE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalingMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_proto_goTypes,
		DependencyIndexes: file_protobuf_proto_depIdxs,
		EnumInfos:         file_protobuf_proto_enumTypes,
		MessageInfos:      file_protobuf_proto_msgTypes,
	}.Build()
	File_protobuf_proto = out.File
	file_protobuf_proto_rawDesc = nil
	file_protobuf_proto_goTypes = nil
	file_protobuf_proto_depIdxs = nil
}
